# -----------------------------------------------------------------------------
# Chart Configuration
# -----------------------------------------------------------------------------

nameOverride: ""
fullnameOverride: ""

replicaCount: 1
revisionHistoryLimit: 3

# -----------------------------------------------------------------------------
# Image
# -----------------------------------------------------------------------------

image:
  repository: 848684726346.dkr.ecr.ap-south-1.amazonaws.com/project/cicdproject
  tag: frontend-proxy-latest
  pullPolicy: Always

# -----------------------------------------------------------------------------
# Service Account
# -----------------------------------------------------------------------------

serviceAccount:
  create: false
  name: default

# -----------------------------------------------------------------------------
# Service
# -----------------------------------------------------------------------------

service:
  type: ClusterIP
  name: http
  port: 8080
  targetPort: 8080

# -----------------------------------------------------------------------------
# Resources
# -----------------------------------------------------------------------------

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# -----------------------------------------------------------------------------
# Security Context
# -----------------------------------------------------------------------------

securityContext:
  runAsUser: 101
  runAsGroup: 101
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false

# -----------------------------------------------------------------------------
# Environment Variables
# -----------------------------------------------------------------------------

env:

  OTEL_COLLECTOR_NAME: "opentelemetry-demo-otelcol"

  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"

  ENVOY_PORT: "8080"

  FLAGD_HOST: "opentelemetry-demo-flagd"
  FLAGD_PORT: "8013"

  FLAGD_UI_HOST: "opentelemetry-demo-flagd"
  FLAGD_UI_PORT: "4000"

  FRONTEND_HOST: "opentelemetry-demo-frontend"
  FRONTEND_PORT: "8080"

  GRAFANA_SERVICE_HOST: "opentelemetry-demo-grafana"
  GRAFANA_SERVICE_PORT: "80"

  IMAGE_PROVIDER_HOST: "opentelemetry-demo-imageprovider"
  IMAGE_PROVIDER_PORT: "8081"

  JAEGER_SERVICE_HOST: "opentelemetry-demo-jaeger-query"
  JAEGER_SERVICE_PORT: "16686"

  LOCUST_WEB_HOST: "opentelemetry-demo-loadgenerator"
  LOCUST_WEB_PORT: "8089"

  OTEL_COLLECTOR_PORT_GRPC: "4317"
  OTEL_COLLECTOR_PORT_HTTP: "4318"

# -----------------------------------------------------------------------------
# Labels
# -----------------------------------------------------------------------------

podLabels:
  app: frontendproxy

# -----------------------------------------------------------------------------
# Scheduling
# -----------------------------------------------------------------------------

nodeSelector: {}

affinity: {}

tolerations: []

# -----------------------------------------------------------------------------
# Volumes
# -----------------------------------------------------------------------------

volumes: []

volumeMounts: []

# -----------------------------------------------------------------------------
# Image Pull Secrets
# -----------------------------------------------------------------------------

imagePullSecrets: []

# -----------------------------------------------------------------------------
# Pod Annotations
# -----------------------------------------------------------------------------

podAnnotations: {}