apiVersion: v1
kind: Service
metadata:
  name: {{ include "opentelemetry-frontend.fullname" . }}
  labels:
    {{- include "opentelemetry-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: tcp-service
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "opentelemetry-frontend.selectorLabels" . | nindent 4 }}